package doc

import (
	"fmt"
	"strings"
)

// Typst renders the document as a Typst source file.
//
// It writes and never runs, which is the same bargain the diagram output
// makes: Typst is a prerequisite of the environment, not a library speclink
// links against and has to keep in step with. What comes out is a complete,
// compilable document rather than a fragment, so the command that renders the
// PDF is `typst compile` and nothing has to be assembled around it first.
//
// The reason this exists next to Markdown is cross references. An audit
// document cites a requirement from a process and a figure from a chapter, and
// Markdown can only emit an anchor that nobody checks. Typst resolves a
// reference or fails to compile, which turns a dangling citation from
// something a reviewer might notice into something the build refuses.
type Typst struct {
	// Title page fields. Empty ones are left off rather than filled with a
	// placeholder, because a specification with an invented author is worse
	// than one with none.
	Author string
	Date   string
}

func (Typst) Ext() string { return "typ" }

func (r Typst) Render(d *Doc) string {
	b := &strings.Builder{}
	r.preamble(b, d)

	for _, blk := range d.Blocks {
		switch t := blk.(type) {
		case *Heading:
			// A chapter is level 2 in the document because level 1 is the
			// title, which Typst sets separately on the title page. Passing
			// the level through unchanged left every chapter one rank too
			// deep and numbered the whole document 0.1, 0.2, 0.3.
			fmt.Fprintf(b, "%s %s", strings.Repeat("=", t.Level-1), typEscape(t.Text))
			if t.ID != "" {
				fmt.Fprintf(b, " <%s>", label(t.ID))
			}
			b.WriteString("\n\n")
		case *Para:
			fmt.Fprintf(b, "%s\n\n", r.inlines(t.Text))
		case *Note:
			fmt.Fprintf(b, "#note[%s]\n\n", r.inlines(t.Text))
		case *List:
			for _, it := range t.Items {
				fmt.Fprintf(b, "- %s\n", r.inlines(it.Text))
				for _, sub := range it.Sub {
					fmt.Fprintf(b, "  - %s\n", r.inlines(sub))
				}
			}
			b.WriteString("\n")
		case *Table:
			r.table(b, t)
		default:
			panic(fmt.Sprintf("doc: typst has no case for %T", blk))
		}
	}
	return b.String()
}

// preamble sets the document up as something an auditor is handed.
//
// Numbered headings, a running header and a page count are the difference
// between a printout and a document that can be cited in a review, and they
// are the reason this backend exists at all. It is kept short on purpose:
// house style belongs in a template a project can replace, not in a tool that
// would then own everybody's typography.
func (r Typst) preamble(b *strings.Builder, d *Doc) {
	fmt.Fprintf(b, "// Generated by speclink. Do not edit.\n")
	fmt.Fprintf(b, "#set document(title: %q)\n", d.Title)
	b.WriteString("#set page(numbering: \"1 / 1\", header: align(right, text(9pt, ")
	fmt.Fprintf(b, "%q)))\n", d.Title)
	b.WriteString("#set par(justify: true)\n")
	// Justification stretches the spaces in a narrow table cell until a path
	// looks like it has one in it, which for a document whose whole purpose
	// is naming files exactly is not a cosmetic problem.
	b.WriteString("#show table: set par(justify: false)\n")
	b.WriteString("#set heading(numbering: \"1.1\")\n")
	b.WriteString("#show heading: it => block(above: 1.4em, below: 0.8em, it)\n")
	b.WriteString("#show link: it => text(fill: blue.darken(20%), it)\n")
	b.WriteString("#let note(body) = block(width: 100%, inset: 8pt, radius: 3pt,\n")
	b.WriteString("  fill: luma(245), stroke: (left: 2pt + luma(180)), body)\n\n")

	fmt.Fprintf(b, "#align(center)[\n  #text(22pt, weight: \"bold\")[%s]\n", typEscape(d.Title))
	if r.Author != "" {
		fmt.Fprintf(b, "  #v(0.6em)\n  #text(11pt)[%s]\n", typEscape(r.Author))
	}
	if r.Date != "" {
		fmt.Fprintf(b, "  #v(0.3em)\n  #text(9pt)[%s]\n", typEscape(r.Date))
	}
	b.WriteString("]\n\n#outline(depth: 2)\n#pagebreak()\n\n")
}

func (r Typst) table(b *strings.Builder, t *Table) {
	cols := make([]string, len(t.Head))
	aligns := make([]string, len(t.Head))
	for i := range t.Head {
		cols[i] = "auto"
		if t.AlignOf(i) == Right {
			aligns[i] = "right"
		} else {
			aligns[i] = "left"
		}
	}
	fmt.Fprintf(b, "#table(\n  columns: (%s),\n  align: (%s),\n",
		strings.Join(cols, ", "), strings.Join(aligns, ", "))

	head := make([]string, len(t.Head))
	for i, h := range t.Head {
		// A blank corner cell is a real thing in these tables: the summary is
		// a list of measures whose first column has no name. Emitting [**]
		// for it would be an empty strong, which Typst reads as the start of
		// something and then does not find the end of.
		if h == "" {
			head[i] = "[]"
			continue
		}
		head[i] = "[*" + typEscape(h) + "*]"
	}
	fmt.Fprintf(b, "  table.header(%s),\n", strings.Join(head, ", "))

	for _, row := range t.Rows {
		cells := make([]string, len(row))
		for i, c := range row {
			cells[i] = "[" + r.inlines(c) + "]"
		}
		fmt.Fprintf(b, "  %s,\n", strings.Join(cells, ", "))
	}
	b.WriteString(")\n\n")
}

func (r Typst) inlines(in []Inline) string {
	b := &strings.Builder{}
	for _, i := range in {
		b.WriteString(r.inline(i))
	}
	return b.String()
}

func (r Typst) inline(i Inline) string {
	switch t := i.(type) {
	case Text:
		return typEscape(string(t))
	case Code:
		return "`" + string(t) + "`"
	case Emph:
		// Typst inverts Markdown: _ is emphasis, * is strong.
		return "_" + typEscape(string(t)) + "_"
	case Strong:
		return "*" + typEscape(string(t)) + "*"
	case Link:
		return fmt.Sprintf("#link(%q)[%s]", t.URL, typEscape(t.Text))
	case Break:
		return "#linebreak()"
	case Ref:
		return "@" + label(t.ID)
	default:
		panic(fmt.Sprintf("doc: typst has no case for inline %T", i))
	}
}

// typEscape protects the characters Typst reads as markup.
func typEscape(s string) string {
	b := &strings.Builder{}
	for _, r := range s {
		switch r {
		case '\\', '#', '*', '_', '`', '$', '<', '>', '@', '[', ']', '~':
			b.WriteRune('\\')
		}
		b.WriteRune(r)
	}
	return b.String()
}

// label makes an identifier Typst will accept as a label.
//
// Requirement identifiers are written by people and contain dots and slashes,
// which Typst would read as the end of the label. The mapping is not reversed
// anywhere, so it only has to be stable and collision free for the identifiers
// a requirement tree actually holds.
func label(id string) string {
	b := &strings.Builder{}
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	return "req-" + b.String()
}
