package doc

import (
	"fmt"
	"strings"
)

// Typst renders the document as a Typst source file.
//
// It writes and never runs, which is the same bargain the diagram output
// makes: Typst is a prerequisite of the environment, not a library speclink
// links against and has to keep in step with. What comes out is a complete,
// compilable document rather than a fragment, so the command that renders the
// PDF is `typst compile` and nothing has to be assembled around it first.
//
// The reason this exists next to Markdown is cross references. An audit
// document cites a requirement from a process and a figure from a chapter, and
// Markdown can only emit an anchor that nobody checks. Typst resolves a
// reference or fails to compile, which turns a dangling citation from
// something a reviewer might notice into something the build refuses.
type Typst struct {
	// Title page fields. Empty ones are left off rather than filled with a
	// placeholder, because a specification with an invented author is worse
	// than one with none.
	Author   string
	Date     string
	Subtitle string
}

func (Typst) Ext() string { return "typ" }

func (r Typst) Render(d *Doc) string {
	b := &strings.Builder{}
	r.preamble(b, d)

	for _, blk := range d.Blocks {
		switch t := blk.(type) {
		case *Heading:
			// A chapter is level 2 in the document because level 1 is the
			// title, which Typst sets separately on the title page. Passing
			// the level through unchanged left every chapter one rank too
			// deep and numbered the whole document 0.1, 0.2, 0.3.
			fmt.Fprintf(b, "%s %s", strings.Repeat("=", t.Level-1), typEscape(t.Text))
			if t.ID != "" {
				fmt.Fprintf(b, " <%s>", label(t.ID))
			}
			b.WriteString("\n\n")
		case *Para:
			fmt.Fprintf(b, "%s\n\n", r.inlines(t.Text))
		case *Note:
			fmt.Fprintf(b, "#note[%s]\n\n", r.inlines(t.Text))
		case *List:
			for _, it := range t.Items {
				fmt.Fprintf(b, "- %s\n", r.inlines(it.Text))
				for _, sub := range it.Sub {
					fmt.Fprintf(b, "  - %s\n", r.inlines(sub))
				}
			}
			b.WriteString("\n")
		case *Figure:
			// Width only. Giving a height as well makes the figure reserve
			// that much page whether the drawing needs it or not, and a wide
			// flat diagram then sits in the middle of half a blank page.
			fmt.Fprintf(b, "#figure(\n  image(%q, width: 100%%),\n  caption: [%s],\n)",
				t.Path, typEscape(t.Caption))
			if t.ID != "" {
				fmt.Fprintf(b, " <%s>", label(t.ID))
			}
			b.WriteString("\n\n")
		case *Table:
			r.table(b, t)
		default:
			panic(fmt.Sprintf("doc: typst has no case for %T", blk))
		}
	}
	return b.String()
}

// preamble sets the document up as something an auditor is handed.
//
// Numbered headings, a running header and a page count are the difference
// between a printout and a document that can be cited in a review, and they
// are the reason this backend exists at all. It is kept short on purpose:
// house style belongs in a template a project can replace, not in a tool that
// would then own everybody's typography.
func (r Typst) preamble(b *strings.Builder, d *Doc) {
	b.WriteString("// Generated by speclink. Do not edit.\n")
	fmt.Fprintf(b, "#set document(title: %q)\n", d.Title)
	b.WriteString(`
#let accent = rgb("#1f4e79")
#let muted = luma(105)

// The running header names the chapter the page is in. Done natively rather
// than with a package, because this document has to compile on a machine with
// no network — an audit build that needs to reach a package registry is one
// that stops working the day the registry does.
#let chapterHere() = {
  // The heading a page opens with sits *after* the header in document order,
  // so asking for the last one before here names the previous chapter on
  // exactly the pages a reader is most likely to check. Prefer a chapter that
  // starts on this page, and only then fall back.
  let all = query(heading.where(level: 1))
  let p = here().page()
  let opening = all.filter(h => h.location().page() == p)
  if opening.len() > 0 {
    opening.first().body
  } else {
    let earlier = all.filter(h => h.location().page() < p)
    if earlier.len() > 0 { earlier.last().body }
  }
}

#set page(
  paper: "a4",
  margin: (top: 28mm, bottom: 24mm, inside: 26mm, outside: 22mm),
  numbering: "1",
  number-align: center,
  header: context {
    if counter(page).get().first() > 1 {
      set text(8.5pt, fill: muted)
      grid(columns: (1fr, auto), align: (left, right),
        smallcaps(document.title),
        emph(chapterHere()))
      v(-6pt)
      line(length: 100%, stroke: 0.4pt + luma(200))
    }
  },
)

#set text(font: "Libertinus Serif", size: 10.5pt, lang: "en")
#set par(justify: true, leading: 0.62em, spacing: 1.1em, first-line-indent: 0pt)

// Headings use the same family as the body. A sans face would look more
// modern, but the only sans a Typst installation is guaranteed to have is
// whatever the machine happens to carry, and a document that sets differently
// on the auditor's machine than on the author's is worse than a plain one.
#show heading: set text(fill: accent)
#set heading(numbering: "1.1")
#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  block(above: 0pt, below: 16pt)[
    #text(9pt, fill: muted, weight: "medium", tracking: 1.2pt)[
      #upper[Chapter #counter(heading).display("1")]
    ]
    #v(2pt)
    #text(19pt, weight: "semibold")[#it.body]
    #v(4pt)
    #line(length: 100%, stroke: 1.2pt + accent)
  ]
}
#show heading.where(level: 2): it => block(above: 1.5em, below: 0.7em,
  text(13pt, weight: "semibold", it))
#show heading.where(level: 3): it => block(above: 1.2em, below: 0.5em,
  text(11pt, weight: "semibold", it))
#show heading.where(level: 4): it => block(above: 1em, below: 0.4em,
  text(10.5pt, weight: "semibold", style: "italic", it))

// Colour alone for links. Underlining every requirement identifier in a table
// that is nothing but identifiers turns the column into a rule.
#show link: it => text(fill: accent, it)
#show raw: set text(font: "DejaVu Sans Mono", size: 8.5pt)

// Tables are read down a column, so the vertical rules come out and the
// header is separated by weight instead of by a box.
#set table(
  stroke: (x, y) => (
    top: if y == 0 { 0.9pt + accent } else if y == 1 { 0.5pt + luma(150) } else { 0.3pt + luma(215) },
    bottom: none, left: none, right: none,
  ),
  inset: (x: 7pt, y: 5.5pt),
  fill: (x, y) => if y == 0 { accent.lighten(94%) },
)
#show table: set par(justify: false)
#show table.cell.where(y: 0): set text(9pt, weight: "semibold")

#let note(body) = block(width: 100%, inset: (x: 10pt, y: 8pt), radius: 2pt,
  fill: accent.lighten(96%), stroke: (left: 2.5pt + accent.lighten(40%)),
  text(9.5pt, body))

#set figure(gap: 10pt)
#show figure.caption: it => text(8.5pt, fill: muted, it)
#set outline(indent: auto)
#show outline.entry.where(level: 1): it => { v(8pt, weak: true); strong(it) }

`)

	r.titlePage(b, d)
}

// titlePage is the first thing anybody sees, and the only part of this
// document that is pure presentation.
func (r Typst) titlePage(b *strings.Builder, d *Doc) {
	b.WriteString("#page(header: none, numbering: none, footer: none)[\n")
	b.WriteString("  #v(1fr)\n")
	b.WriteString("  #block(width: 100%, stroke: (left: 3pt + accent), inset: (left: 16pt))[\n")
	fmt.Fprintf(b, "    #text(9pt, fill: muted, weight: \"medium\", tracking: 2pt)[#upper[Specification]]\n")
	fmt.Fprintf(b, "    #v(6pt)\n    #text(30pt, weight: \"bold\")[%s]\n", typEscape(d.Title))
	if r.Subtitle != "" {
		fmt.Fprintf(b, "    #v(8pt)\n    #text(13pt, fill: muted)[%s]\n", typEscape(r.Subtitle))
	}
	b.WriteString("  ]\n  #v(1fr)\n")

	rows := [][2]string{}
	if r.Author != "" {
		rows = append(rows, [2]string{"Issued by", r.Author})
	}
	if r.Date != "" {
		rows = append(rows, [2]string{"Date", r.Date})
	}
	rows = append(rows, [2]string{"Derived by", "speclink generate"})
	b.WriteString("  #grid(columns: (auto, 1fr), row-gutter: 6pt, column-gutter: 14pt,\n")
	for _, kv := range rows {
		fmt.Fprintf(b, "    text(8.5pt, fill: muted)[%s], text(9.5pt)[%s],\n",
			typEscape(kv[0]), typEscape(kv[1]))
	}
	b.WriteString("  )\n")
	b.WriteString("  #v(10pt)\n  #line(length: 100%, stroke: 0.5pt + luma(200))\n")
	b.WriteString("  #v(6pt)\n  #text(8pt, fill: muted)[")
	b.WriteString("Every sentence in this document is written somewhere else in the source. ")
	b.WriteString("It is regenerated, never edited.]\n]\n\n")

	b.WriteString("#page(numbering: none)[\n  #text(15pt, weight: \"semibold\", fill: accent)[Contents]\n")
	b.WriteString("  #v(8pt)\n  #outline(title: none, depth: 2)\n]\n\n#counter(page).update(1)\n\n")
}

func (r Typst) table(b *strings.Builder, t *Table) {
	cols := make([]string, len(t.Head))
	aligns := make([]string, len(t.Head))
	for i := range t.Head {
		cols[i] = "auto"
		if t.AlignOf(i) == Right {
			aligns[i] = "right"
		} else {
			aligns[i] = "left"
		}
	}
	fmt.Fprintf(b, "#table(\n  columns: (%s),\n  align: (%s),\n",
		strings.Join(cols, ", "), strings.Join(aligns, ", "))

	head := make([]string, len(t.Head))
	for i, h := range t.Head {
		// A blank corner cell is a real thing in these tables: the summary is
		// a list of measures whose first column has no name. Emitting [**]
		// for it would be an empty strong, which Typst reads as the start of
		// something and then does not find the end of.
		if h == "" {
			head[i] = "[]"
			continue
		}
		head[i] = "[*" + typEscape(h) + "*]"
	}
	fmt.Fprintf(b, "  table.header(%s),\n", strings.Join(head, ", "))

	for _, row := range t.Rows {
		cells := make([]string, len(row))
		for i, c := range row {
			cells[i] = "[" + r.inlines(c) + "]"
		}
		fmt.Fprintf(b, "  %s,\n", strings.Join(cells, ", "))
	}
	b.WriteString(")\n\n")
}

func (r Typst) inlines(in []Inline) string {
	b := &strings.Builder{}
	for _, i := range in {
		b.WriteString(r.inline(i))
	}
	return b.String()
}

func (r Typst) inline(i Inline) string {
	switch t := i.(type) {
	case Text:
		return typEscape(string(t))
	case Code:
		return "`" + string(t) + "`"
	case Emph:
		// Typst inverts Markdown: _ is emphasis, * is strong.
		return "_" + typEscape(string(t)) + "_"
	case Strong:
		return "*" + typEscape(string(t)) + "*"
	case Link:
		return fmt.Sprintf("#link(%q)[%s]", t.URL, typEscape(t.Text))
	case Break:
		return "#linebreak()"
	case Mark:
		return typMark(t)
	case Ref:
		// link(<label>)[text] rather than @label. The bare reference renders
		// as the section number of the target — "Section 15.1" — which in a
		// register whose whole job is to name requirements tells the reader
		// nothing about which row they are looking at. This keeps the words
		// and keeps the guarantee: Typst refuses to compile a link to a label
		// that does not exist, exactly as it refuses a bare reference.
		return fmt.Sprintf("#link(<%s>)[%s]", label(t.ID), typEscape(t.Text))
	default:
		panic(fmt.Sprintf("doc: typst has no case for inline %T", i))
	}
}

// typMark spells a verdict as a glyph the eye can find down a column.
//
// Colour carries the same information as the shape, never only the shape, so
// the table survives being printed in black and white — which is how an audit
// document is usually read.
func typMark(m Mark) string {
	switch m {
	case Yes:
		return `#text(fill: rgb("#1a7f37"))[#sym.checkmark]`
	case Partly:
		return `#text(fill: rgb("#9a6700"))[#sym.circle.filled.tiny]`
	case No:
		return `#text(fill: rgb("#b42318"))[#sym.times]`
	case Unknown:
		return `#text(fill: luma(130))[?]`
	case NotRequired:
		return `#text(fill: luma(160))[#sym.dash.en]`
	default:
		panic(fmt.Sprintf("doc: typst has no case for mark %d", int(m)))
	}
}

// typEscape protects the characters Typst reads as markup.
func typEscape(s string) string {
	b := &strings.Builder{}
	for _, r := range s {
		switch r {
		case '\\', '#', '*', '_', '`', '$', '<', '>', '@', '[', ']', '~':
			b.WriteRune('\\')
		}
		b.WriteRune(r)
	}
	return b.String()
}

// label makes an identifier Typst will accept as a label.
//
// Requirement identifiers are written by people and contain dots and slashes,
// which Typst would read as the end of the label. The mapping is not reversed
// anywhere, so it only has to be stable and collision free for the identifiers
// a requirement tree actually holds.
func label(id string) string {
	b := &strings.Builder{}
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	return "req-" + b.String()
}
