package classfile

import (
	"fmt"
	"strings"
)

// Access flags, JVMS §4.1, §4.5, §4.6. Only the ones anything here asks about.
const (
	AccPublic     = 0x0001
	AccPrivate    = 0x0002
	AccProtected  = 0x0004
	AccStatic     = 0x0008
	AccFinal      = 0x0010
	AccInterface  = 0x0200
	AccAbstract   = 0x0400
	AccSynthetic  = 0x1000
	AccAnnotation = 0x2000
	AccEnum       = 0x4000
)

// Class is one compiled type.
type Class struct {
	// Major is the class file version. 52 is Java 8, 61 is Java 17, 65 is
	// Java 21. Android output is usually 52 whatever the toolchain, because the
	// JVM target defaults to 1.8 and desugaring handles the rest.
	Major, Minor uint16

	Access uint16
	// Name is the binary name with dots, e.g. "com.example.Quote$Inner".
	Name string
	// Super is the binary name of the superclass, empty only for Object.
	Super string
	// Interfaces are the binary names of the directly implemented interfaces.
	Interfaces []string

	Fields  []Member
	Methods []Member

	// Annotations are the class level annotations, from both retentions.
	Annotations []Annotation
	// SourceFile is the file name the class was compiled from, without any
	// path — "Quote.java", never "src/main/java/com/example/Quote.java".
	SourceFile string
	// Signature is the generic signature when the class has type parameters or
	// a generic supertype, empty otherwise.
	Signature string

	Pool Pool
}

// Member is a field or a method.
type Member struct {
	Access uint16
	Name   string
	// Descriptor is the erased JVM descriptor, e.g. "(Ljava/lang/String;)V".
	Descriptor string
	// Signature is the generic signature when there is one.
	Signature string
	// Annotations are the member's own annotations, from both retentions.
	Annotations []Annotation
	// Line is the first source line of a method body, 0 when unknown.
	//
	// It is always 0 for a field. LineNumberTable is an attribute of Code
	// (JVMS §4.7.12) and a field has no code, so a field's declaration line is
	// not merely missing from this reader — it does not exist in the format.
	Line int
}

// IsSynthetic reports whether the member was generated by a compiler rather
// than written. Kotlin produces a great many of these — $default bridges for
// default arguments, access$ accessors, $VALUES for enums — and none of them
// were written by anybody, so none of them can carry an intent.
func (m Member) IsSynthetic() bool { return m.Access&AccSynthetic != 0 }

// Annotation is one annotation with its arguments.
type Annotation struct {
	// Type is the binary name of the annotation type, e.g. "speclink.Satisfies".
	Type string
	// Values are the named arguments. Arguments left at their default are
	// absent: the default lives on the annotation type, not on the use.
	Values map[string]Value
	// Visible says which retention it was found under.
	//
	// Both are read, and that is not optional. Java's default retention is
	// CLASS and Kotlin's is RUNTIME — opposite defaults — so Room, Compose,
	// Hilt and every Kotlin nullability annotation sit in the invisible table.
	// A reader that took only the visible one would find almost everything on
	// Spring and nothing at all on Android.
	Visible bool
}

// Value is one annotation argument.
//
// Kind follows the element_value tag of JVMS §4.7.16.1, which is what decides
// how to read the rest: 'c' is a class reference, 'e' an enum constant, '@' a
// nested annotation, '[' an array, and the remainder are constants.
type Value struct {
	Kind byte
	// Const holds a string, int32, int64, float32, float64, bool, byte, int16
	// or rune, depending on the tag.
	Const any
	// Class is the binary name for a class reference, e.g. "com.example.RQuoteSubmit".
	Class string
	// EnumType and EnumConst name an enum constant.
	EnumType, EnumConst string
	// Nested is the annotation of a '@' value.
	Nested *Annotation
	// Array holds the elements of a '[' value.
	Array []Value
}

// String renders a value's text, for the cases where one is expected.
func (v Value) String() string {
	if s, ok := v.Const.(string); ok {
		return s
	}
	return ""
}

// Read parses a class file.
func Read(b []byte) (*Class, error) {
	r := &reader{b: b}

	if got := r.u4(); got != Magic {
		return nil, fmt.Errorf("not a class file: magic is %#x, want %#x", got, Magic)
	}
	c := &Class{}
	c.Minor = r.u2()
	c.Major = r.u2()
	c.Pool = r.readPool()
	if r.err != nil {
		return nil, r.err
	}

	c.Access = r.u2()
	c.Name = binaryName(c.Pool, r.u2())
	if super := r.u2(); super != 0 {
		c.Super = binaryName(c.Pool, super)
	}
	for n := int(r.u2()); n > 0 && r.err == nil; n-- {
		c.Interfaces = append(c.Interfaces, binaryName(c.Pool, r.u2()))
	}

	c.Fields = r.readMembers(c.Pool)
	c.Methods = r.readMembers(c.Pool)

	r.readAttributes(c.Pool, func(name string, body *reader) {
		switch name {
		case "RuntimeVisibleAnnotations":
			c.Annotations = append(c.Annotations, body.readAnnotations(c.Pool, true)...)
		case "RuntimeInvisibleAnnotations":
			c.Annotations = append(c.Annotations, body.readAnnotations(c.Pool, false)...)
		case "SourceFile":
			c.SourceFile, _ = c.Pool.UTF8(body.u2())
		case "Signature":
			c.Signature, _ = c.Pool.UTF8(body.u2())
		}
	})

	if r.err != nil {
		return nil, r.err
	}
	return c, nil
}

func (r *reader) readMembers(pool Pool) []Member {
	n := int(r.u2())
	if r.err != nil {
		return nil
	}
	out := make([]Member, 0, n)
	for ; n > 0 && r.err == nil; n-- {
		m := Member{Access: r.u2()}
		m.Name, _ = pool.UTF8(r.u2())
		m.Descriptor, _ = pool.UTF8(r.u2())

		r.readAttributes(pool, func(name string, body *reader) {
			switch name {
			case "RuntimeVisibleAnnotations":
				m.Annotations = append(m.Annotations, body.readAnnotations(pool, true)...)
			case "RuntimeInvisibleAnnotations":
				m.Annotations = append(m.Annotations, body.readAnnotations(pool, false)...)
			case "Signature":
				m.Signature, _ = pool.UTF8(body.u2())
			case "Code":
				m.Line = body.readFirstLine(pool)
			}
		})
		out = append(out, m)
	}
	return out
}

// readAttributes walks an attribute table, handing each one to fn as a reader
// bounded to its own bytes.
//
// Unknown attributes are skipped by their declared length, which JVMS §4.7.1
// requires and which is the whole of this reader's forward compatibility: every
// version since 45.3 has only added attributes, so skipping what is not
// recognised is enough to read Java 8 through 25 without a version table.
func (r *reader) readAttributes(pool Pool, fn func(name string, body *reader)) {
	for n := int(r.u2()); n > 0 && r.err == nil; n-- {
		nameIdx := r.u2()
		length := int(r.u4())
		raw := r.bytes(length)
		if r.err != nil {
			return
		}
		name, ok := pool.UTF8(nameIdx)
		if !ok {
			continue
		}
		body := &reader{b: raw}
		fn(name, body)
		if body.err != nil {
			r.fail("attribute %s: %v", name, body.err)
		}
	}
}

// readFirstLine returns the lowest line number of a method body.
//
// The table is not sorted by line, and the first entry is the line of the first
// instruction, which for a Kotlin method with an inlined prologue is not the
// declaration. The lowest is the closest thing to "where this was written" that
// the format offers.
func (r *reader) readFirstLine(pool Pool) int {
	r.u2()                             // max_stack
	r.u2()                             // max_locals
	r.skip(int(r.u4()))                // code
	for n := int(r.u2()); n > 0; n-- { // exception table
		r.skip(8)
	}

	line := 0
	r.readAttributes(pool, func(name string, body *reader) {
		if name != "LineNumberTable" {
			return
		}
		for n := int(body.u2()); n > 0 && body.err == nil; n-- {
			body.u2() // start_pc
			if l := int(body.u2()); l > 0 && (line == 0 || l < line) {
				line = l
			}
		}
	})
	return line
}

// readAnnotations reads an annotation table, JVMS §4.7.16.
func (r *reader) readAnnotations(pool Pool, visible bool) []Annotation {
	n := int(r.u2())
	out := make([]Annotation, 0, n)
	for ; n > 0 && r.err == nil; n-- {
		out = append(out, r.readAnnotation(pool, visible))
	}
	return out
}

func (r *reader) readAnnotation(pool Pool, visible bool) Annotation {
	desc, _ := pool.UTF8(r.u2())
	a := Annotation{Type: typeNameOf(desc), Visible: visible, Values: map[string]Value{}}

	for n := int(r.u2()); n > 0 && r.err == nil; n-- {
		name, _ := pool.UTF8(r.u2())
		a.Values[name] = r.readValue(pool)
	}
	return a
}

// readValue reads one element_value, JVMS §4.7.16.1.
func (r *reader) readValue(pool Pool) Value {
	tag := r.u1()
	v := Value{Kind: tag}

	switch tag {
	case 'B', 'C', 'D', 'F', 'I', 'J', 'S', 'Z':
		raw, _ := pool.Const(r.u2())
		v.Const = narrow(tag, raw)
	case 's':
		v.Const, _ = pool.UTF8(r.u2())
	case 'c':
		// A class reference is stored as a return descriptor, not as a
		// CONSTANT_Class: "Lcom/example/Foo;" rather than "com/example/Foo".
		desc, _ := pool.UTF8(r.u2())
		v.Class = typeNameOf(desc)
	case 'e':
		desc, _ := pool.UTF8(r.u2())
		v.EnumType = typeNameOf(desc)
		v.EnumConst, _ = pool.UTF8(r.u2())
	case '@':
		nested := r.readAnnotation(pool, true)
		v.Nested = &nested
	case '[':
		for n := int(r.u2()); n > 0 && r.err == nil; n-- {
			v.Array = append(v.Array, r.readValue(pool))
		}
	default:
		r.fail("unknown element_value tag %q", tag)
	}
	return v
}

// narrow returns a constant as the type its tag says it is.
//
// The pool stores every small integral constant as CONSTANT_Integer, so a
// boolean arrives as int32 1 and a char as an int32 code point. Handing those
// on unnarrowed would make every caller repeat the same switch.
func narrow(tag byte, raw any) any {
	i, ok := raw.(int32)
	if !ok {
		return raw
	}
	switch tag {
	case 'Z':
		return i != 0
	case 'B':
		return int8(i)
	case 'S':
		return int16(i)
	case 'C':
		return rune(i)
	}
	return raw
}

// binaryName resolves a CONSTANT_Class index to a name with dots.
func binaryName(pool Pool, i uint16) string {
	internal, ok := pool.Class(i)
	if !ok {
		return ""
	}
	return strings.ReplaceAll(internal, "/", ".")
}

// typeNameOf turns a field descriptor into a binary name.
//
// "Lcom/example/Foo;" becomes "com.example.Foo". Arrays keep their brackets and
// primitives are returned as their descriptor letter, because neither is ever a
// thing this reader looks up.
func typeNameOf(desc string) string {
	if len(desc) > 2 && desc[0] == 'L' && desc[len(desc)-1] == ';' {
		return strings.ReplaceAll(desc[1:len(desc)-1], "/", ".")
	}
	return desc
}
